#!/usr/bin/python
# This file is part of pybliographer
# 
# Copyright (C) 1998-2003 Frederic GOBRY
# Email : gobry@pybliographer.org
# 	   
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2 
# of the License, or (at your option) any later version.
#   
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details. 
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
# 

""" Main module for pybliographic.

This module handles the set of opened documents.
"""

import sys

from PyblioUI.Gnome import Document

files = sys.argv [2:]

docs = []

def reaper (doc):

    docs.remove (doc)
    if not docs: Gnome.exit ()

    return


if files:
    for f in files:
        d = Document.Document ()
        d.open (f, None)
        d.register ('close', reaper)
        
        docs.append (d)

else:
    d = Document.Document ()
    d.register ('close', reaper)
    
    docs.append (d)


from PyblioUI import Gnome

Gnome.run ()
